### ISSUE TITLE
Missing file - "Ticker.h"

### ISSUE THREAD

**Issue by Uup115** [littlevgl/arduino#10]
Hello,

"Ticker.h" is missing.  As a result, the example **ESP32_TFT_eSPI** will not compile.

Best Regards

**Comment by Pablo2048** [comment]
Hi,
Ticker is standard library from ESP32 core - see https://github.com/espressif/arduino-esp32/tree/master/libraries/Ticker so there is probably problem with your ESP32 Core installation.

**Comment by Uup115** [comment]
Hello,

Good to go!  Thanks for the help!
