### ISSUE TITLE
ESP32 with lv_aruino  can't set label style.

### ISSUE THREAD

**Issue by TridentTD** [littlevgl/arduino#13]
I have just tried the example "ESP32_TFT_eSPI"  from the current master lv_arduino, 
it can run fine.

However when I want to change label style to red color
by the following code. It occure error at run-time.

```C
// base code : lv_arduino/examples/ESP32_TFT_eSPI/ESP32_TFT_eSPI.ino

#include <lvgl.h>
#include <Ticker.h>
#include <TFT_eSPI.h>

#define LVGL_TICK_PERIOD 20

Ticker tick; /* timer for interrupt handler */
TFT_eSPI tft = TFT_eSPI(); /* TFT instance */
static lv_disp_buf_t disp_buf;
static lv_color_t buf[LV_HOR_RES_MAX * 10];

#if USE_LV_LOG != 0
/* Serial debugging */
void my_print(lv_log_level_t level, const char * file, uint32_t line, const char * dsc)
{

  Serial.printf("%s@%d->%s\r\n", file, line, dsc);
  delay(100);
}
#endif

/* Display flushing */
void my_disp_flush(lv_disp_drv_t *disp, const lv_area_t *area, lv_color_t *color_p)
{
  uint16_t c;

  tft.startWrite(); /* Start new TFT transaction */
  tft.setAddrWindow(area->x1, area->y1, (area->x2 - area->x1 + 1), (area->y2 - area->y1 + 1)); /* set the working window */
  for (int y = area->y1; y <= area->y2; y++) {
    for (int x = area->x1; x <= area->x2; x++) {
      c = color_p->full;
      tft.writeColor(c, 1);
      color_p++;
    }
  }
  tft.endWrite(); /* terminate TFT transaction */
  lv_disp_flush_ready(disp); /* tell lvgl that flushing is done */
}

/* Interrupt driven periodic handler */
static void lv_tick_handler(void)
{

  lv_tick_inc(LVGL_TICK_PERIOD);
}

/* Reading input device (simulated encoder here) */
bool read_encoder(lv_indev_drv_t * indev, lv_indev_data_t * data)
{
  static int32_t last_diff = 0;
  int32_t diff = 0; /* Dummy - no movement */
  int btn_state = LV_INDEV_STATE_REL; /* Dummy - no press */

  data->enc_diff = diff - last_diff;;
  data->state = btn_state;

  last_diff = diff;

  return false;
}

void setup() {

  Serial.begin(115200); /* prepare for possible serial debug */

  lv_init();

#if USE_LV_LOG != 0
  lv_log_register_print(my_print); /* register print function for debugging */
#endif

  tft.begin(); /* TFT init */
  tft.setRotation(1); /* Landscape orientation */

  lv_disp_buf_init(&disp_buf, buf, NULL, LV_HOR_RES_MAX * 10);

  /*Initialize the display*/
  lv_disp_drv_t disp_drv;
  lv_disp_drv_init(&disp_drv);
  disp_drv.hor_res = 320;
  disp_drv.ver_res = 240;
  disp_drv.flush_cb = my_disp_flush;
  disp_drv.buffer = &disp_buf;
  lv_disp_drv_register(&disp_drv);


  /*Initialize the touch pad*/
  lv_indev_drv_t indev_drv;
  lv_indev_drv_init(&indev_drv);
  indev_drv.type = LV_INDEV_TYPE_ENCODER;
  indev_drv.read_cb = read_encoder;
  lv_indev_drv_register(&indev_drv);

  /*Initialize the graphics library's tick*/
  tick.attach_ms(LVGL_TICK_PERIOD, lv_tick_handler);

  /* Create simple label */
  lv_obj_t *label = lv_label_create(lv_scr_act(), NULL);
  lv_label_set_text(label, "Hello Arduino! (V6.0)");
  lv_obj_align(label, NULL, LV_ALIGN_CENTER, 0, 0);

  //---------------- My test for changing label's style--------------------------------
  lv_style_t label_style; 
  lv_style_copy(&label_style, &lv_style_plain);  
  lv_style.text.color = LV_COLOR_RED;
  lv_obj_set_style( label,  &label_style);
  //-------------------------------------------------------------------------------------
}


void loop() {

  lv_task_handler(); /* let the GUI do its work */
  delay(5);
}
```
  
error at run-time.  
//------------------------------------------------------------
rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1100
load:0x40078000,len:9232
load:0x40080400,len:6400
entry 0x400806a8
Guru Meditation Error: Core  1 panic'ed (InstrFetchProhibited). Exception was unhandled.
Core 1 register dump:
PC      : 0x00000014  PS      : 0x00060730  A0      : 0x800d7d51  A1      : 0x3ffb1c40  
A2      : 0x3ffc488c  A3      : 0x3ffb1c68  A4      : 0x00000048  A5      : 0x00000065  
A6      : 0x006f0056  A7      : 0x008000ea  A8      : 0x800f62c0  A9      : 0x3ffb1eb0  
A10     : 0x3ffc488c  A11     : 0x3ffb1c68  A12     : 0x00000048  A13     : 0x00000065  
A14     : 0x00000000  A15     : 0x00110094  SAR     : 0x00000001  EXCCAUSE: 0x00000014  
EXCVADDR: 0x00000014  LBEG    : 0x4000c2e0  LEND    : 0x4000c2f6  LCOUNT  : 0xffffffff  

Backtrace: 0x00000014:0x3ffb1c40 0x400d7d4e:0x3ffb1c60 0x400d8f33:0x3ffb1c90 0x400d4de6:0x3ffb1ce0 0x400d93f8:0x3ffb1db0 0x400d359d:0x3ffb1e10 0x400d3627:0x3ffb1e60 0x400d3660:0x3ffb1eb0 0x400d36d7:0x3ffb1ed0 0x400d3a4f:0x3ffb1f00 0x400d8bb5:0x3ffb1f50 0x400d8c75:0x3ffb1f70 0x400d0f3f:0x3ffb1f90 0x400de431:0x3ffb1fb0 0x40088ed5:0x3ffb1fd0

Rebooting...
ets Jun  8 2016 00:22:57
//------------------------------------------------------------

How to fix this issue?

Thank you very much.

**Comment by Pablo2048** [comment]
You have to decode the stack trace - without decoding the stack trace is useless. Maybe also @kisvegabor can give us some advice after looking to the source code. And also maybe this is already fixed bug in last few days - lv_arduino is (unfortunately) not based on release, but master which get updates almost every day...

**Comment by TridentTD** [comment]
OK, I have already fixed this issue.

I moved   "lv_style_t label_style;" 
to global variable declare. It can be fixed.

Thank you very much.

**Comment by Pablo2048** [comment]
Ok, I'm closing this then...
