### ISSUE TITLE
Wrong link in Arduino Libraries

### ISSUE THREAD

**Issue by kisvegabor** [littlevgl/arduino#16]
Hi,

I've just seen this page uses a very old link to LittlevGL:  
 https://www.arduinolibraries.info/libraries/littlev-gl

@Pablo2048 is this your library? 

EDIT:
Probably it comes from here:
https://github.com/littlevgl/lv_arduino/blob/master/library.properties#L8

**Comment by Pablo2048** [comment]
Ah, yes - its from here. I have to correct this. What is the right url? https://littlevgl.com/ ?

**Comment by kisvegabor** [comment]
Yes, it's  https://littlevgl.com/ 

Thank you!

**Comment by Pablo2048** [comment]
Done - V2.0.1 with updated url was released.

**Comment by kisvegabor** [comment]
Great! Thank you!
