### ISSUE TITLE
lv_prelaod animation

### ISSUE THREAD

**Issue by Uup115** [littlevgl/arduino#18]
Hello

The example code doesn't spin.  Please, how to enable the spin animation?  

https://docs.littlevgl.com/en/html/object-types/preload.html

Thanks

**Comment by Pablo2048** [comment]
I was using this, but with 5.3 version
```C
// Boot up screen
  lv_obj_t *label = lv_label_create(mainCircle, NULL);
  lv_label_set_text(label, "Connecting to WiFi...");
  lv_obj_align(label, mainCircle, LV_ALIGN_CENTER, 0, -20);

  lv_style_copy(&preloaderstyle, &lv_style_plain);
  preloaderstyle.line.width = 6;                         /*?? px thick arc*/
  preloaderstyle.line.color = LV_COLOR_HEX3(0x258);       /*Blueish arc color*/

  preloaderstyle.body.border.color = LV_COLOR_HEX3(0xBBB); /*Gray background color*/
  preloaderstyle.body.border.width = 6;
  preloaderstyle.body.padding.hor = 0;

  /*Create a Preloader object*/
  lv_obj_t *preload = lv_preload_create(mainCircle, NULL);
  lv_obj_set_size(preload, 50, 50);
  lv_obj_align(preload, mainCircle, LV_ALIGN_CENTER, 0, 20);
  lv_preload_set_style(preload, LV_PRELOAD_STYLE_MAIN, &preloaderstyle);

  lvglMutex = xSemaphoreCreateMutex();
  xTaskCreate(gui_task, "lvgl", 10 * 1024, NULL, 5, NULL); // Start GUI task
```
I'll try to update the code to V6.0 and let you know...

**Comment by kisvegabor** [comment]
I've tested it with the latest master branch (not in Arduino) and it works for me.

@Uup115 Could you manually update lvgl from the latest master and try again?

**Comment by Uup115** [comment]
@kisvegabor  Per your request, I updated from the latest master...  With the update, I see  only **one** complete CCW rotation.  The animation stops after the first rotation.

**Comment by embeddedt** [comment]
@Uup115 When it "stops", has the processor crashed, or does LittlevGL keep running?

**Comment by Uup115** [comment]
@embeddedt  LittlevGL keeps running as normal.  No crashes.

**Comment by embeddedt** [comment]
How is `lv_tick_inc` called on Arduino?

**Comment by Uup115** [comment]
@embeddedt  Thanks for your last message, regarding "lv_tick_inc" .  I discovered an error in the way I configured the Timer interrupt.  Totally my fault.  Really, really sorry. :-(

I've already kicked myself several times.  I'll go ahead and kick myself several more times for you, kisvegabor, and Pablo2048.

It does seem strange that everything else was working, even though the interrupt wasn't firing properly???

**Comment by Pablo2048** [comment]
:-) Ok, so it works now? Can you please try with pure lv_arduino? If it works only with actual sources I have to do new release with actual master...

**Comment by Uup115** [comment]
@Pablo2048  I reverted back to lv_arduino (v2.0)  Yes, everything is working with both (latest master and lv_arduino).  Good to go!  

Thanks for everyone's help!

**Comment by Pablo2048** [comment]
... so I'm closing this as solved...

**Comment by embeddedt** [comment]
> I've already kicked myself several times. I'll go ahead and kick myself several more times for you, kisvegabor, and Pablo2048.

Now we'll never be able to add a disclaimer stating that no developers were harmed in the making of this product. :smile:

Seriously, don't worry about it. It's a pretty difficult issue to find when it surfaces.
