### ISSUE TITLE
Character misalignment in calendar[LVGL_V6.0]

### ISSUE THREAD

**Issue by qwert1213131** [littlevgl/arduino#21]
Is v6.0.1 a solution to this problem?
I haven't had a chance to try it out yet.
Are there any plans to update lv_arduino recently?
Thank you
![批注 2019-08-03 200609](https://user-images.githubusercontent.com/3905169/62411734-5dcb5880-b62a-11e9-8b79-6ec319559cca.png)

**Comment by embeddedt** [comment]
Please fill out the bug template, either here or on the forum. With the information you've described I don't see any issue... the numbers are all centered if you draw a line down the center. I think the behavior you've described is intentional.
