### ISSUE TITLE
Images in progmem

### ISSUE THREAD

**Issue by aaron-neal** [littlevgl/arduino#25]
This is a question rather than an issue so please redirect me somewhere else if it's irrelevant here.

I have succesfully got this library working on an 8266 (ili9341 inc. touch) and it runs well after lowering the buffer sizes.

I was wandering if there are any examples of pulling images from progmem or SPIFFS , with or without an lvgl PNG decoder?

Cheers, Aaron

**Comment by embeddedt** [comment]
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

It's possible to sign in to the forum with your GitHub account... you don't need to make a separate account.
