### ISSUE TITLE
V2.0.3 in library manager

### ISSUE THREAD

**Issue by elgerg** [littlevgl/arduino#29]
Hi,

I went to update to the latest release but it's not there:

![image](https://user-images.githubusercontent.com/24628571/68550229-de071400-03f8-11ea-97ef-139080b9f7b8.png)

Is there something i need to do to be able to get the latest version though the lib manager?

Thanks
Alex

**Comment by embeddedt** [comment]
My guess is that it needs to be published in some manner before it becomes visible in the Arduino library manager. But I'm not familiar with Arduino so I could be wrong.

I suppose you could temporarily replace the files in the interim if you need a quick solution.

**Comment by Pablo2048** [comment]
Hi. I was out of hardware so I was unable to test the new version before release. I think that I can test it before weekend so please be patient...
