### ISSUE TITLE
Lib updates not appearing in Arduino IDE library manager 

### ISSUE THREAD

**Issue by Stego72** [littlevgl/arduino#33]
Hi 

The latest versions do not appear in the Arduino IDE Library Manager - only versions up to 2.0.1 appear. Hence update functionality is broken.

BR

Stego72

**Comment by Pablo2048** [comment]
Hi,
thanks for spotting this. I've made new request (because of changed repository name) here https://github.com/arduino/Arduino/issues/9850 so we have to waitnow...

**Comment by Pablo2048** [comment]
Well, my request was completed 7 days ago, but I still don't see the new version in my Arduino IDE. Can you @Stego72 please check it?

**Comment by Stego72** [comment]
Hi - Nope 

Now shows versions up to 2.0.3 (2.0.1 before) but none of the versions after that

BR

Stego72

**Comment by Pablo2048** [comment]
Done - there is v2.1.4 in Arduino IDE Library manager present so I'm closing this as solved.

**Comment by kisvegabor** [comment]
Thank you Pablo!
