### ISSUE TITLE
Use millis() as custom tick

### ISSUE THREAD

**Issue by kisvegabor** [littlevgl/arduino#34]
Hi Pablo,

What would you think about setting `millis()` [lv_conf.h](https://github.com/littlevgl/lv_arduino/blob/master/lv_conf.h#L202-L206) as a custom tick function?

This way `Ticker` wouldn't be required.

**Comment by Pablo2048** [comment]
Hi Gabor,
sorry for late reply. I thought that using Ticker lower the CPU load. Unfortunately Ticker is only ESP8266/ESP32 specific so I take a look and change the example to use `millis()`...

**Comment by kisvegabor** [comment]
No problem! :) 

> Unfortunately Ticker is only ESP8266/ESP32 specific so I take a look and change the example to use millis()...

In this case, a more portable solution would be really better. Thank you in advance!

**Comment by Pablo2048** [comment]
I'm working on it - it is done actually in my git repo, but I'm waiting for LCD module to arrive...

**Comment by kisvegabor** [comment]
Great, thank you for the update!
