### ISSUE TITLE
Display distorted with STM32F103 and ILI9341

### ISSUE THREAD

**Issue by HamidSaffari** [littlevgl/arduino#35]
Hi and salute to the creators.
I tried to run this with STM32F103 and ILI9341 using https://github.com/stm32duino/Arduino_Core_STM32
core and your ESP32_TFT_eSPI example works fine to showing hello-world but when I used ESP32_TFT_eSPI_Slider example I have got distorted image like the picture:

![IMG_20200325_08000824](https://user-images.githubusercontent.com/35362339/77499862-ea07e580-6e70-11ea-91a2-8b8a6291042b.jpg)

and even the same distorted result without using any theme (only whole image is brighter).
And I'm sure the TFT_eSPI library is alright because all the graphic tests of that library works fine with my setup.

**Comment by Pablo2048** [comment]
Hi,
did you modified the screen resolution as mentioned here https://github.com/littlevgl/lv_arduino/tree/master/examples/ESP32_TFT_eSPI_Slider#example-for-lv_arduino-using-a-slider ?

**Comment by HamidSaffari** [comment]
Oh man, I forget to modified resolution in ESP32_TFT_eSPI_Slider.ino and only did that in lv_conf.h. Now it Works. Thanks.
I'm trying to make an example with STM32 and as soon as it's finish I will make a pull-request.
also I find out that compile result when changing memory wrappers by: 
#define LV_MEM_CUSTOM   1 //compile result => FLASH: 107720 bytes, RAM: 13444 bytes 
vs
#define LV_MEM_CUSTOM   0 //compile result => FLASH: 107904 bytes, RAM: 46216 bytes 

saving  32777 bytes of RAM  which most of them for LV_MEM_SIZE = 32K.
now is there any instability or slowness in performance if we use custom wrappers?

**Comment by Pablo2048** [comment]
Great - so this issue is solved. PR with your example for STM32 is welcome :-) . About your memory question - better ask directly in master lvgl repository.

**Comment by kisvegabor** [comment]
There are 2 purposes of the built-in memory functions:
1. Platform independent behavior
2. Memory monitoring feature (free/used memory, fragmentation, etc)

So other `malloc/free` implementations can work equally well if memory monitoring is not important for you.

(The forum would be really better a place for these general questions.)

**Comment by HamidSaffari** [comment]
Thanks Gabor & all the contributors for making this great and complicated library. Yes multi-platform support makes it more complicated, you already surpassed non-free GUI makers software like Embedded-Wizard, SEGGER-emWin, TouchGFX in many cases and I hope by finishing your drag&drop app [lv_gui_builder] you beat them completely.
So keep it coming.

**Comment by kisvegabor** [comment]
Thank you Hamid! :slightly_smiling_face: 
If you have experience with other GUI libraries I'd love to read about it a Forum post.
