### ISSUE TITLE
ESP32 ili9341 display not working correctly (maybe disp_flush problem)

### ISSUE THREAD

**Issue by nikisalli** [littlevgl/arduino#4]
With the example sketch loaded, 7/8 of the display is filled in a white/black stripy pattern while the other part seems to load the correct image piece by piece because it is always white (that is the correct background color in the example sketch) and with debugging messages on (so with a 100ms delay) i can see a part of the Hello World string appearing for just a frame.

The espi library settings are correct because i used it before and tried some sketches too to confirm that.

The lv_conf.h is just the standard one with debug enabled.

thank you in advance, (the library looks awesome!)

![photo_2019-03-16_20-33-43](https://user-images.githubusercontent.com/31286021/54480623-dcb22700-482a-11e9-863b-aa55ea4ac5f2.jpg)

**Comment by Pablo2048** [comment]
Hi,
that strippy pattern mean unwritten area. Please check SPI speed settings in TFT_eSPI library. Did you use unmodified example (just with correct TFT_eSPI settings) or do you have another peripheral on the same SPI bus?

**Comment by nikisalli** [comment]
> Hi,
> that strippy pattern mean unwritten area. Please check SPI speed settings in TFT_eSPI library. Did you use unmodified example (just with correct TFT_eSPI settings) or do you have another peripheral on the same SPI bus?

Hi thank you for the answer,
i have no other devices on the spi bus, the display runs in 8bit bus mode, maybe that is the problem?

**Comment by Pablo2048** [comment]
I've never tried to communicate with ILI9341 over parallel bus so i can't say. Can you please try this:
  * initialize the display
  * fill some memory area with solid color
  * call disp_flush and check, if the TFT behave correctly

**Comment by kisvegabor** [comment]
Do you call `lv_flush_ready` when you finish `flushing?`

**Comment by nikisalli** [comment]
It is the example code i just found in the examples directory:
https://github.com/littlevgl/lv_arduino/blob/master/examples/ESP32_TFT_eSPI/ESP32_TFT_eSPI.ino

**Comment by Pablo2048** [comment]
Ok, so please try steps I've suggested and post results here...

**Comment by nikisalli** [comment]
Yes, i have to try today to see what happens, thanks!

**Comment by nikisalli** [comment]
ok i tried and nothing changes, only the top small part changes in color as expected.
i wanted to ask, is the stripy pattern something the display does or is the lvgl library doing it?

**Comment by nikisalli** [comment]
anyways the problem is how disp_flush writes colors, writecolor() doesn't work correctly because the library works if i use drawPixel instead but i guess it is a bit slower

**Comment by Pablo2048** [comment]
The strippy pattern is result from display init. If writecolor() doesn't work right then the problem is in TFT_eSPI library, or (maybe) in the initialisation part of the TFT_eSPI. Display has to be set to the 16 bit RGB565 color IIRC.

**Comment by nikisalli** [comment]
ok thanks, i think i'll keep using drawpixel until i find something faster that actually works

**Comment by sonastyle** [comment]
I'm  getting the same issue, how did you solve that?
