### ISSUE TITLE
V7  Update

### ISSUE THREAD

**Issue by momosh13** [littlevgl/arduino#43]
Please update lv_arduino to V7.01, when possible.
Thank you.

**Comment by Pablo2048** [comment]
I'm waiting for final 7.0.1 release - 7.0.1-dev version is prepared in my repository. Only the first (and simplest) example is tested because of my limited hardware availability.

**Comment by kisvegabor** [comment]
Okay. The plan is to release at least a bugfix version every 2 weeks. So v7.0.1 is scheduled to 1 Jun.

**Comment by kisvegabor** [comment]
@Pablo2048 
What do you have to do to release a new Arduino version? If it's possible I can update lvgl's [release script](https://github.com/lvgl/lvgl/blob/master/scripts/release.py) to apply some changes in this repo too.

**Comment by Pablo2048** [comment]
I have to get the new version, check configuration if it's still valid, check at least the simplest example if it still works and if so I have to modify `library.json` and `library.properties` with new numbers. As I wrote here https://forum.lvgl.io/t/arduino-questions/2405/7?u=pablo2048 I hope that I'll do all this until end of this week.

**Comment by kisvegabor** [comment]
Would you agree to automatically update library.json on patch releases? 
They don't add new features or config options just fixes some bugs.

**Comment by Pablo2048** [comment]
Okay, no problem with that...

**Comment by kisvegabor** [comment]
Great! I'll update the script then.

**Comment by Pablo2048** [comment]
New PR has been created. Can anybody test it (especially with the STM32 example) or should I merge it?

**Comment by Pablo2048** [comment]
New version (3.0.0) based on LVGL 7.0.1 was released right now. Unfortunately the STM32 example was not tested/updated because I don't have this hardware so please be kind... :-)
