### ISSUE TITLE
Lib update via Arduino IDE Library manager seems to be broken (again)

### ISSUE THREAD

**Issue by Pablo2048** [littlevgl/arduino#45]
Unfortunately, because of renaming `littlevgl` to `lvgl`, the library update via Library manager is broken again and I have to solve it... :-(

**Comment by kisvegabor** [comment]
Uh... Sorry for the inconvenience. 
I hope there won't be such renames in the near future.

**Comment by Pablo2048** [comment]
:-) - filled new request in https://github.com/arduino/Arduino/issues/10269 so we have to wait...

**Comment by Pablo2048** [comment]
Seems to be done - https://github.com/arduino/Arduino/issues/10269#issuecomment-636536104
