### ISSUE TITLE
Plotting data dynamically on TFT Screen

### ISSUE THREAD

**Issue by mimansamaheshwari** [littlevgl/arduino#47]
First of all a bow down and thanks for creating such a useful library. I am working on a small menu interface in which I wish to plot live data of sensors on the TFT screen. I read the Charts object but couldn't figure out how to plot the dynamic data on the screen. Is plotting dynamic data like sensors values or any variable possible with Charts object. Can you suggest what approach should I follow for making a data plotter using this library? I am working with TFT on ESP32.

**Comment by Pablo2048** [comment]
Please put such kind of questions about lvgl directly to the forum https://forum.lvgl.io/ . Closing for now...
