### ISSUE TITLE
how can you speed up lv_arduino ?

### ISSUE THREAD

**Issue by simonchen007** [littlevgl/arduino#52]
hello,

We have a strange issue these days. We try 3 ways for testing LVGL v7 benchmark for esp32.
1) Arduino-esp32 framework + lv_arduino + TFT_eSPI ,  we got about 30 FPS.
2) Esp-idf framework + arduino-esp32(as components) + LVGL（https://github.com/lvgl/lvgl）+ TFT_eSPI, we got about 9 FPS.
3) Lv_port_esp32 + arduino-esp32(as components) + TFT_eSPI, we got about 9 FPS.

As we known, Arduino-esp32 is packaged from  ESP-idf, it should be faster then Arduino-esp32 in  theory. But it's 2 times slower currently.

How can you speed up lv_arduino ?

thanks

**Comment by Pablo2048** [comment]
Hi,
I did nothing special so if your measurements are right, then only one thing pops up in my head - loop() task (if the loop() is executed in one task) has higher priority in Arduino-esp32 framework.

**Comment by simonchen007** [comment]
so, is that possible to make [Esp-idf framework + arduino-esp32(as components) + LVGL（https://github.com/lvgl/lvgl）+ TFT_eSPI ]  have the same speed ?

**Comment by Pablo2048** [comment]
I really don't know - you have to search in arduino-esp32 sources for setup/loop thread parameters and compare it with arduino-esp32 as component. That is all I can suggest...

**Comment by simonchen007** [comment]
okay, I will try it. I saw you have esp-id repository too, I guess you have tried that, that's why I ask you .
but of course, I will try to do as you said, 

thanks
