### ISSUE TITLE
touch doesn't work

### ISSUE THREAD

**Issue by mourazo** [littlevgl/arduino#61]
I trying to make it work the example, the TFT display is ili9341 240x320, but the touchpad doesn’t work and I can’t move the slider. In all examples of the TFT_eSPI library the touch Works correctly, only doesn’t work with lvgl library. I use lvgl v.7 download from the oficial page, if you can help me I would appreciate a lot. This are my pins conections from esp32 nodeMCU to ili9341. Wich can be my problem? Thanks in advance

#define TFT_MISO 19
#define TFT_MOSI 23
#define TFT_SCLK 18
#define TFT_CS 5
#define TFT_DC 4
#define TFT_RST 22
#define TOUCH_CS 14

**Comment by kisvegabor** [comment]
We use GitHub Issues for development-related discussions.

Please ask your question in the [Forum](https://forum.lvgl.io) to make it visible for a larger community. You can simply log in with your GitHub account.
