### ISSUE TITLE
LVGL task Handling

### ISSUE THREAD

**Issue by engr-mujahidabdullah** [littlevgl/arduino#62]
Hi,
I hope all of you are in good health. I am working on ESP32 and SPI_TFT_ILI9341, I my project i have to cover mutliple tasks i.e sensor fusion , tft display, wifi etc etc.. Hence i am at the bigning of my project and i have a problem here i create test task and tft_task in which i call custom functions the problem i that which i observe i that the only task which run is the first one which i call.
![SS_setup](https://user-images.githubusercontent.com/61884536/100526119-cce99a80-31e7-11eb-8708-929d3564aae8.PNG)

from above figure the only task un is TFT_display 
![TFT_ss](https://user-images.githubusercontent.com/61884536/100526166-1d60f800-31e8-11eb-8000-3bc9c28bcc50.PNG)
 and tft_task is as above 
in next task i only do some serial printing periodically.
Kindly guide me how to manage multiple tasks with lvgl.

**Comment by embeddedt** [comment]
If you comment out the LVGL related code does the problem still occur? If so then this is a platform/FreeRTOS issue, not an LVGL one.

**Comment by engr-mujahidabdullah** [comment]
I think this issue is partially related to lvgl.

**Comment by embeddedt** [comment]
Please check that it happens only when LVGL is in use first. There's not much happening in your code sample, so unless LVGL is corrupting memory somewhere, I'd be surprised if it was causing the problem.

**Comment by kisvegabor** [comment]
If `lv_task_handler` halts it's usually becasue of the missing `lv_disp_flush_ready()` in your `disp_flush()` function.
Do you call it?

**Comment by engr-mujahidabdullah** [comment]
Yes, I did.  But the matter is that not both tasks run only the first one
which i call run either next_task or tft_task this only happen when i
attach tft_task.

**Comment by embeddedt** [comment]
Change `TFT_Task` to this:

```c
void TFT_Task(void *pvParameters)
{
    while(1) {
        vTaskDelay(5);
    }
}
```

See whether the problem still occurs.

**Comment by Pablo2048** [comment]
The problem is that the memory allocated for stack is too big IMHO (100000 WORDS!!! - not bytes, for each task) did you check the result of `xTaskCreate` function?
EDIT: please see https://www.freertos.org/a00125.html

**Comment by engr-mujahidabdullah** [comment]
Yes, I did.
However after long debugging I found that the problem is with lv_init()
when i call this function the code blocks or runs only the first task.

**Comment by Pablo2048** [comment]
> Yes, I did.
>
And what was the result? I don't believe that the system with 520kB of RAM will allow allocation of 400000 bytes two times... Also I don't know why you are allocating so insane huge stack - I'm using 10 * 1024 and it seems to be more than enough. Because you did not publish the code with `lv_init()` call, I'm unable to help more - just one suggestion: don't forget to use mutex in the task where the `lv_task_handler()` is called (and use this mutex in foreground/second task where it needs to be used). For example I'm doing it like this:
Setup part:
```cpp
  lvglMutex = xSemaphoreCreateMutex();
  xTaskCreate(gui_task, "lvgl", 10 * 1024, NULL, 5, NULL); // Start GUI task
```
and my lvgl handler task looks like:
```cpp
void gui_task(void *dev)
{

  while (1)
  {
    xSemaphoreTake(lvglMutex, portMAX_DELAY);
    lv_task_handler();
    xSemaphoreGive(lvglMutex);
    vTaskDelay(5);
    lv_tick_inc(5);
  }
  vTaskDelete(NULL);
}
```

**Comment by engr-mujahidabdullah** [comment]
Thanks to all,
I resolved the issue by initializing more tasks. Is any example of auto
scrolling of textbox when keyboard popup.

**Comment by embeddedt** [comment]
`lv_demo_widgets` does this by [resizing the tabview](https://github.com/lvgl/lv_examples/blob/25ae1dc9842b23d3c27effcd1b1a98c7e8688151/src/lv_demo_widgets/lv_demo_widgets.c#L562-L593) to be half the screen height when the keyboard is created. When the keyboard is deleted, the tabview is returned to its old size.

You can see `lv_demo_widgets` online [here](https://lvgl.github.io/lv_examples/lv_demo_widgets/index.html).
